=== MBJ-hub/2021_LMSGI_MBJ/ud04/03.dtd
<!ELEMENT description (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT fecha (dia, mes, anyo)>
<!ELEMENT HechoHistorico (descripcion, fecha)>
<!ELEMENT internet (HechoHistorico*)>

=== MBJ-hub/2021_LMSGI_MBJ/ud04/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE internet SYSTEM '03.dtd'>

<internet>
    <HechoHistorico>
        <descripcion>Se funda Youtube</descripcion>
        <fecha>
            <dia>15</dia>
            <mes>2</mes>
            <anyo>2005</anyo>
        </fecha>
    </HechoHistorico>
    <HechoHistorico>
        <descripcion>Se funda Google</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>9</mes>
            <anyo>1998</anyo>
        </fecha>
    </HechoHistorico>  
    <HechoHistorico>
        <descripcion>Se funda Facebook</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>2</mes>
            <anyo>2004</anyo>
        </fecha>
    </HechoHistorico>    
</internet>
