<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE grupo [
    <!ELEMENT grupo (estudiante*)>
    <!ELEMENT estudiante (#PCDATA)>
    <!ATTLIST estudiante cod ID #REQUIRED
                         idref IDREFS #IMPLIED>
    <!ATTLIST grupo
     xsi:noNamespaceSchemaLocation CDATA #IMPLIED
     xmlns:xsi CDATA #IMPLIED>

]>

<grupo xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xsi:noNamespaceSchemaLocation='07.xsd'>
    <estudiante cod="E1" idref="E2 E3">
        Mario
    </estudiante>
    <estudiante cod="E4" idref="E2">
        Aparicio
    </estudiante>
    <estudiante cod="E3" idref="E2 E3">
        Bruce 
    </estudiante>
    <estudiante cod="E2" idref="E3">
        Clark 
    </estudiante>
    
</grupo>
