=== MBJ-hub/2021_LMSGI_MBJ/ud04/FormularioMario.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!ELEMENT Multimedia (animales)*>
<!ELEMENT animales (#PCDATA)>
<!ATTLIST animales
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED>
<!ELEMENT pregunta (#PCDATA)>
<!ELEMENT lista (#PCDATA)>
<!ATTLIST pregunta 
    lista (reptil|mamifero|anfibio|pez|aves|insectos) #REQUIRED>
<!ELEMENT reptil (#PCDATA)>
<!ELEMENT mamifero (#PCDATA)>
<!ELEMENT anfibio (#PCDATA)>
<!ELEMENT pez (#PCDATA)>
<!ELEMENT aves (#PCDATA)>
<!ELEMENT insectos (#PCDATA)>
<!ELEMENT pregunta2 (#PCDATA)>
<!ELEMENT autor EMPTY>
<!ATTLIST autor 
        datos (nombre|apellidos) #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT derechos (#PCDATA)>
<!ELEMENT audios (#PCDATA)>
<!ATTLIST audios
          espacio (Kb|Mb|Gb) "Gb">
<!ELEMENT videos (#PCDATA)>
<!ELEMENT tamanyo (#PCDATA)>
<!ATTLIST videos
          tamanyo (Mb|Gb|Tb) "Gb">
<!ELEMENT imagenes (#PCDATA)>
<!ATTLIST imagenes
          ocupa (Kb|Mb|Gb) "Gb">
<!ELEMENT texto (#PCDATA)>

=== MBJ-hub/2021_LMSGI_MBJ/ud04/FormularioMario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Multimedia SYSTEM 'FormularioMario.dtd'>
<!--
Animales
@Mario Badallo Jiménez
-->
<Multimedia
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xs:noNamespaceSchemaLocation='FormularioMario.xsd'>
    
    <animales>
        <imagenes>GATOO.jpg</imagenes>
        <imagenes>Jungla.jpg</imagenes>
        <imagenes>LAGATOOO.jpg</imagenes>
        <imagenes>mamifero.jpg</imagenes>
        <imagenes>PAJARO.jpg</imagenes>
        <imagenes>pez.jpg</imagenes>
        <imagenes>reptil.jpg</imagenes>
        
        <pregunta lista="reptil">
            <lista>
                <reptil>reptil</reptil>
                <mamifero>mamifero</mamifero>
                <anfibio>anfibio</anfibio>
                <pez>pez</pez>
                <aves>aves</aves>
                <insectos>insectos</insectos>
            </lista>
        </pregunta>
        <pregunta2>
            <audios espacio="Kb">21,5Kb</audios>
            <audios espacio="Kb">30,4Kb</audios>
            <audios espacio="Kb">31,2Kb</audios>
        </pregunta2>
        
        <videos tamanyo="Gb">2,3Gb</videos>
        <videos tamanyo="Gb">3,2Gb</videos>
        <videos tamanyo="Gb">3Gb</videos>
        
        <texto>Derechos de autor reservados a Mario Badallo Jiménez</texto>
        
    </animales>
</Multimedia>
