=== MBJ-hub/2021_LMSGI_MBJ/ud04/modelocomplejo.xsd
<?xml version="1.0"?>
<!--
@author Mario Badallo JimÃ©nez.
Fecha. 11/02/2021
Validacion de modelos.
Hemos inplementado restricciones y fijado valores a los elementos.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="modelo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curso">
                    <xs:simpleType> 
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1"/>
                            <xs:maxInclusive value="2"/>
                        </xs:restriction>
                    </xs:simpleType> 
                </xs:element>
                <xs:element name="ciclo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="DAW"/>
                            <xs:enumeration value="ASIR"/>
                            <xs:enumeration value="DAM"/>
                            <xs:enumeration value="SMR"/>
                        </xs:restriction>
                    </xs:simpleType> 
                </xs:element>
                <xs:element name="nombreA">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3"/>
                            <xs:maxLength value="100"/>
                            <xs:pattern value="[A-Z]([a-zA-Z ])*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="codigoPostal">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]{5}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="comentario">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:whiteSpace value="collapse"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                 <xs:element name="temperatura">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                           <xs:totalDigits value="5"/>
                           <xs:fractionDigits value="2"/>
                           <xs:minInclusive value="-37"/>
                           <xs:maxInclusive value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="codigoAsignatura">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern value="EDD|LMGSI|SIF|FOL|BBDD|PROG"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="profesor">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="codP">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="[A-Z]{3}"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MBJ-hub/2021_LMSGI_MBJ/ud04/modelo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<modelo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='modelocomplejo.xsd'>
    <curso>1</curso>
    <ciclo>ASIR</ciclo>
    <nombreA>Lenguaje de Marcas y Gestion de la Informacion</nombreA>
    <codigoPostal>49600</codigoPostal>
    <comentario>Este ciclo tiene  una insercion laboral de     100%</comentario>
    <temperatura>32.20</temperatura>
    <codigoAsignatura>EDD</codigoAsignatura>
    <profesor codP="ARN" modI="LMGSI">Amor Rodriguez</profesor>
</modelo>
